#!/bin/bash

# Check Environment Variables used by Relion
RELION_MINIMUM_DEDICATED=24
MOTD=BIENVENUE SUR LE CONTAINER DOCKER DE RELION4 !!! | cowsay
RELION_GCTF_EXECUTABLE=/usr/local/EM/Gctf/bin/Gctf
RELION_ALLOW_CHANGE_MINIMUM_DEDICATED=0
RELION_SUMMOVIE_EXECUTABLE=/usr/local/EM/SUMMOVIE/summovie.exe
RELION_RESMAP_EXECUTABLE=/usr/local/EM/ResMap/ResMap-1.1.4-linux64
RELION_PDFVIEWER_EXECUTABLE=evince
RELION_CTFFIND_EXECUTABLE=/usr/local/bin/ctffind
RELION_UNBLUR_EXECUTABLE=/usr/local/EM/UNBLUR/unblur.exe
RELION_SHELL=bash
RELION_QSUB_TEMPLATE=/public/EM/RELION/relion-prerelease/bin/qsub.csh
RELION_MOTIONCOR2_EXECUTABLE=/usr/local/EM/MOTIONCOR2/bin/MotionCor2_1.4.7
RELION_WARNING_LOCAL_MPI=60




