/*

const select = {
  hidden_name: '.gui_select',
  children: [


  {
    name: 'fn_model',
    title: 'Select classes from job:',
    default:  NODE_OPTIMISER_CPIPE, "',
    help: `STAR files (*_optimiser.star)',
    help: `A _optimiser.star (or for backwards compatibility also a _model.star) file from a previous 2D or 3D classification run to select classes from.`,
  },
  {
    name: 'fn_mic',
    title: 'OR select from micrographs.star:',
    default:  NODE_MICS_CPIPE, "',
    help: `STAR files (*.star)',
    help: `A micrographs.star file to select micrographs from.`,
  },
  {
    name: 'fn_data',
    title: 'OR select from particles.star:',
    default:  NODE_PARTS_CPIPE, "',
    help: `STAR files (*.star)',
    help: `A particles.star file to select individual particles from.`,
  },

  {
    name: 'do_class_ranker',
    title: 'Automatically select 2D classes?',
    default:  false, 
    help: `If set to True, the class_ranker program will be used to make an automated class selection, based on the parameters below. This option only works when selecting classes from a relion_refine job (input optimiser.star on the I.O tab)`,
  },
  {
    name: 'rank_threshold',
    title: 'Minimum threshold for auto-selection: ',
    default:  0.5, 0, 1, 0.05, "Only classes with a pre dicted threshold above this value will be selected.`,
  },
  {
    name: 'select_nr_parts',
    title: 'Select at least this many particles: ',
    default:  -1, -1, 10000, 500, "Even if they have scores below the minimum threshold, select at least this many particles with the best scores.`,
  },
  {
    name: 'select_nr_classes',
    title: 'OR: select at least this many classes: ',
    default:  -1, -1, 24, 1, "Even if they have scores below the minimum threshold, select at least this many classes with the best scores.`,
  },
  {
    name: 'python_exe',
    title: 'Python executable: ',
    default:  std::string(default_location), "This version of python should include torch and numpy. We have found that the one from topaz (which is also used for auto-picking) works well. At the LMB, it is here: /public/EM/anaconda3/envs/topaz/bin/python`,
  },
  {
    name: 'do_recenter',
    title: 'Re-center the class averages?',
    default:  true, "This option is only used when selecting particles from 2D classes. The selected class averages will all re-centered on their center-of-mass. This is useful when you plane to use these class averages as templates for auto-picking.`,
  },
  {
    name: 'do_regroup',
    title: 'Regroup the particles?',
    default:  false, "If set to Yes, then the program will regroup the selected particles in 'more-or-less' the number of groups indicated below. For re-grouping from individual particle _data.star files, a _model.star file with the same prefix should exist, i.e. the particle star file should be generated by relion_refine`,
  },
  {
    name: 'nr_groups',
    title: 'Approximate nr of groups: ',
    default:  1, 50, 20, 1, "It is normal that the actual number of groups may deviate a little from this number. `,
  },
  {
    name: 'do_select_values',
    title: 'Select based on metadata values?',
    default:  false, "If set to Yes, the job will be non-interactive and the selected star file will be based only on the value of the corresponding metadata label. Note that this option is only valid for micrographs or particles STAR files.`,
  },
  {
    name: 'select_label',
    title: 'Metadata label for subset selection:',
    default:  (std::string)"rlnCtfMaxResolution',
    help: `This column from the input STAR file will be used for the subset selection.`,
  },
  {
    name: 'select_minval',
    title: 'Minimum metadata value:',
    default:   (std::string)"-9999.',
    help: `Only lines in the input STAR file with the corresponding metadata value larger than or equal to this value will be included in the subset.`,
  },
  {
    name: 'select_maxval',
    title: 'Maximum metadata value:',
    default:   (std::string)"9999.',
    help: `Only lines in the input STAR file with the corresponding metadata value smaller than or equal to this value will be included in the subset.`,
  },
  {
    name: 'do_discard',
    title: 'OR: select on image statistics?',
    default:  false, "If set to Yes, the job will be non-interactive and all images in the input star file that have average and/or stddev pixel values that are more than the specified sigma-values away from the ensemble mean will be discarded.`,
  },
  {
    name: 'discard_label',
    title: 'Metadata label for images:',
    default:  (std::string)"rlnImageName',
    help: `Specify which column from the input STAR contains the names of the images to be used to calculate the average and stddev values.`,
  },
  {
    name: 'discard_sigma',
    title: 'Sigma-value for discarding images:',
    default:  4, 1, 10, 0.1, "Images with average and/or stddev values that are more than this many times the ensemble stddev away from the ensemble mean will be discarded.`,
  },

  {
    name: 'do_split',
    title: 'OR: split into subsets?',
    default:  false, "If set to Yes, the job will be non-interactive and the star file will be split into subsets as defined below.`,
  },
  {
    name: 'do_random',
    title: 'Randomise order before making subsets?:',
    default:  false, "If set to Yes, the input STAR file order will be randomised. If set to No, the original order in the input STAR file will be maintained.`,
  },
  {
    name: 'split_size',
    title: 'Subset size: ',
    default:  100, 100, 10000, 100, "The number of lines in each of the output subsets. When this is -1, items are divided into a number of subsets specified in the next option.`,
  },
  {
    name: 'nr_split',
    title: 'OR: number of subsets: ',
    default:  -1, 1, 50, 1, "Give a positive integer to specify into how many equal-sized subsets the data will be divided. When the subset size is also specified, only this number of subsets, each with the specified size, will be written, possibly missing some items. When this is -1, all items are used, generating as many subsets as necessary.`,
  },

  {
    name: 'do_remove_duplicates',
    title: 'OR: remove duplicates?',
    default:  false, "If set to Yes, duplicated particles that are within a given distance are removed leaving only one. Duplicated particles are sometimes generated when particles drift into the same position during alignment. They inflate and invalidate gold-standard FSC calculation.`,
  },
  {
    name: 'duplicate_threshold',
    title: 'Minimum inter-particle distance (A)',
    default:  30, 0, 1000, 1, "Particles within this distance are removed leaving only one.`,
  },
  {
    name: 'image_angpix',
    title: 'Pixel size before extraction (A)',
    default:  -1, -1, 10, 0.01, "The pixel size of particles (relevant to rlnOriginX/Y) is read from the STAR file. When the pixel size of the original micrograph used for auto-picking and extraction (relevant to rlnCoordinateX/Y) is different, specify it here. In other words, this is the pixel size after binning during motion correction, but before down-sampling during extraction.`,
  },
}

  ]
};

*/

/*
const mask = {
  hidden_name: '.gui_maskcreate',
  children: [
  {
    name: 'fn_in',
    title: 'Input 3D map:',
    default:  NODE_MAP_CPIPE, "',
    help: `MRC map files (*.mrc)',
    help: `Provide an input MRC map from which to start binarizing the map.`,
  },
  {
    name: 'lowpass_filter',
    title: 'Lowpass filter map (A)',
    default:  15, 10, 100, 5, "Lowpass filter that will be applied to the input map, prior to binarization. To calculate solvent masks, a lowpass filter of 15-20A may work well.`,
  },
  {
    name: 'angpix',
    title: 'Pixel size (A)',
    default:  -1, 0.3, 5, 0.1, "Provide the pixel size of the input map in Angstroms to calculate the low-pass filter. This value is also used in the output image header.`,
  },
  {
    name: 'inimask_threshold',
    title: 'Initial binarisation threshold:',
    default:  0.02, 0., 0.5, 0.01, "This threshold is used to make an initial binary mask from the average of the two unfiltered half-reconstructions. \
If you don't know what value to use, display one of the unfiltered half-maps in a 3D surface rendering viewer and find the lowest threshold that gives no noise peaks outside the reconstruction.`,
  },
  {
    name: 'extend_inimask',
    title: 'Extend binary map this many pixels:',
    default:  3, 0, 20, 1, "The initial binary mask is extended this number of pixels in all directions." );
  {
    name: 'width_mask_edge',
    title: 'Add a soft-edge of this many pixels:',
    default:  3, 0, 20, 1, "The extended binary mask is further extended with a raised-cosine soft edge of the specified width." );
  {
    name: 'do_helix',
    title: 'Mask a 3D helix?',
    default:  false, "Generate a mask for 3D helix which spans across Z axis of the box.`,
  },
  {
    name: 'helical_z_percentage',
    title: 'Central Z length (%):',
    default:  30., 5., 80., 1., "Reconstructed helix suffers from inaccuracies of orientation searches. \
The central part of the box contains more reliable information compared to the top and bottom parts along Z axis. Set this value (%) to the central part length along Z axis divided by the box size. Values around 30% are commonly used but you may want to try different lengths.`,
  },
  ]
};
*/

const joinstar_particles = {
  widget: 'navtab',
  hidden_name: '.gui_joinstar',
  children: [
  {
    name: 'do_part',
    title: 'Combine particle STAR files?',
    widget: 'bool',
    default:  false,
  },
  {
    name: 'fn_part1',
    title: 'Particle STAR file 1: ',
    widget: 'file',
    filetype: 'NODE_PARTS_CPIPE',
    placeholder: 'particle STAR file (*.star)',
    help: `The first of the particle STAR files to be combined.`,
  },
  {
    name: 'fn_part2',
    title: 'Particle STAR file 2: ',
    widget: 'file',
    filetype: 'NODE_PARTS_CPIPE',
    placeholder: 'particle STAR file (*.star)',
    help: `The second of the particle STAR files to be combined.`,
  },
  {
    name: 'fn_part3',
    title: 'Particle STAR file 3: ',
    widget: 'file',
    filetype: 'NODE_PARTS_CPIPE',
    placeholder: 'particle STAR file (*.star)',
    help: `The third of the particle STAR files to be combined. Leave empty if there are only two files to be combined.`,
  },
  {
    name: 'fn_part4',
    title: 'Particle STAR file 4: ',
    widget: 'file',
    filetype: 'NODE_PARTS_CPIPE',
    placeholder: 'particle STAR file (*.star)',
    help: `The fourth of the particle STAR files to be combined. Leave empty if there are only two or three files to be combined.`,
  },
  ]
};



const joinstar_micrographs = {
  widget: 'navtab',
  hidden_name: '.gui_joinstar',
  children: [
    {
      name: 'fn_mic1',
      title: 'Micrograph STAR file 1: ',
      widget: 'file',
      filetype: 'NODE_MICS_CPIPE',
      placeholder: 'micrograph STAR file (*.star)',
      help: `The first of the micrograph STAR files to be combined.`,
    },
    {
      name: 'fn_mic2',
      title: 'Micrograph STAR file 2: ',
      widget: 'file',
      filetype: 'NODE_MICS_CPIPE',
      placeholder: 'micrograph STAR file (*.star)',
      help: `The second of the micrograph STAR files to be combined.`,
    },
    {
      name: 'fn_mic3',
      title: 'Micrograph STAR file 3: ',
      widget: 'file',
      filetype: 'NODE_MICS_CPIPE',
      placeholder: 'micrograph STAR file (*.star)',
      help: `The third of the micrograph STAR files to be combined. Leave empty if there are only two files to be combined.`,
    },
    {
      name: 'fn_mic4',
      title: 'Micrograph STAR file 4: ',
      widget: 'file',
      filetype: 'NODE_MICS_CPIPE',
      placeholder: 'micrograph STAR file (*.star)',
      help: `The fourth of the micrograph STAR files to be combined. Leave empty if there are only two or three files to be combined.`,
    },
  ]
};

const joinstar_movies = {
  widget: 'navtab',
  hidden_name: '.gui_joinstar',
  children: [
    {
      name: 'fn_mov1',
      title: 'Movie STAR file 1: ',
      widget: 'file',
      filetype: 'NODE_MOVIES_CPIPE',
      placeholder: 'movie STAR file (*.star)',
      help: `The first of the micrograph movie STAR files to be combined.`,
    },
    {
      name: 'fn_mov2',
      title: 'Movie STAR file 2: ',
      widget: 'file',
      filetype: 'NODE_MOVIES_CPIPE',
      placeholder: 'movie STAR file (*.star)',
      help: `The second of the micrograph movie STAR files to be combined.`,
    },
    {
      name: 'fn_mov3',
      title: 'Movie STAR file 3: ',
      widget: 'file',
      filetype: 'NODE_MOVIES_CPIPE',
      placeholder: 'movie STAR file (*.star)',
      help: `The third of the micrograph movie STAR files to be combined. Leave empty if there are only two files to be combined.`,
    },
    {
      name: 'fn_mov4',
      title: 'Movie STAR file 4: ',
      widget: 'file',
      filetype: 'NODE_MOVIES_CPIPE',
      placeholder: 'movie STAR file (*.star)',
      help: `The fourth of the micrograph movie STAR files to be combined. Leave empty if there are only two or three files to be combined.`,
    },
  ]
}
const external = {
  children: [
    // I/O
    {
      name: 'fn_exe',
      title: 'External executable:',
      widget: 'file',
      help: `Location of the script that will launch the external program. This script should write all its output in the directory specified with --o. Also, it should write in that same directory a file called RELION_JOB_EXIT_SUCCESS upon successful exit, and RELION_JOB_EXIT_FAILURE upon failure.`,
    },
    // Optional input nodes
    {
      name: 'in_mov',
      title: 'Input movies: ',
      widget: 'file',
      filetype: 'NODE_MOVIES_CPIPE',
      placeholder: 'movie STAR file (*.star)',
      help: `Input movies. This will be passed with a --in_movies argument to the executable.`,
    },
    {
      name: 'in_mic',
      title: 'Input micrographs: ',
      filetype: 'NODE_MICS_CPIPE, "',
      placeholder: 'micrographs STAR file (*.star)',
      help: `Input micrographs. This will be passed with a --in_mics argument to the executable.`,
    },
    {
      name: 'in_part',
      title: 'Input particles: ',
      filetype: 'NODE_PARTS_CPIPE, "',
      placeholder: 'particles STAR file (*.star)',
      help: `Input particles. This will be passed with a --in_parts argument to the executable.`,
    },
    {
      name: 'in_coords',
      title: 'Input coordinates: ',
      filetype: 'NODE_COORDS_CPIPE, "',
      placeholder: 'STAR files (coords_suffix*.star)',
      help: `Input coordinates. This will be passed with a --in_coords argument to the executable.`,
    },
    {
      name: 'in_3dref',
      title: 'Input 3D reference: ',
      filetype: 'NODE_MAP_CPIPE, "',
      placeholder: 'MRC files (*.mrc)',
      help: `Input 3D reference map. This will be passed with a --in_3dref argument to the executable.`,
    },
    {
      name: 'in_mask',
      title: 'Input 3D mask: ',
      filetype: 'NODE_MASK_CPIPE, "',
      placeholder: 'MRC files (*.mrc)',
      help: `Input 3D mask. This will be passed with a --in_mask argument to the executable.`,
    },

    // Optional parameters
    {
      name: 'param1_label',
      title: 'Param1 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param1_value',
      title: 'Param1 - value:' , 
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param2_label',
      title: 'Param2 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param2_value',
      title: 'Param2 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param3_label',
      title: 'Param3 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param3_value',
      title: 'Param3 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param4_label',
      title: 'Param4 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param4_value',
      title: 'Param4 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param5_label',
      title: 'Param5 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param5_value',
      title: 'Param5 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param6_label',
      title: 'Param6 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param6_value',
      title: 'Param6 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param7_label',
      title: 'Param7 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param7_value',
      title: 'Param7 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param8_label',
      title: 'Param8 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param8_value',
      title: 'Param8 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param9_label',
      title: 'Param9 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param9_value',
      title: 'Param9 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param10_label',
      title: 'Param10 - label:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
    {
      name: 'param10_value',
      title: 'Param10 - value:',
      widget: 'text',
      default: '', 
      help: `Define label and value for optional parameters to the script. These will be passed as an argument --label value`,
    },
  ]
};


const tools_tabs = [
  {
    name: 'do_raw',
    title: 'Tools',
    icon: 'bi-wrench-adjustable',
    widget: 'navtab',
    default:  true, 
    children: [
      {
        name: 'do_movies',
        title: 'Subset selection',
        widget: 'fieldset',
        children: [
          {
            name: 'fn_model',
            title: 'Select classes from job',
            widget: 'radio',
            option: '--fn_model',
            group: 'toolkit',
            help: `A _optimiser.star (or for backwards compatibility also a _model.star) file from a previous 2D or 3D classification run to select classes from.`,
            on_click: (ev) => w_navtab_update({settings: joinstar_particles})
          },
          {
            name: 'do_class_ranker',
            title: 'Select automatically from 2D classes',
            widget: 'radio',
            option: '--do_class_ranker',
            group: 'toolkit',
            help: `If set to True, the class_ranker program will be used to make an automated class selection, based on the parameters below. This option only works when selecting classes from a relion_refine job (input optimiser.star on the I.O tab)`,
          },
          {
            name: 'fn_mic',
            title: 'Select from micrographs.star',
            widget: 'radio',
            option: '--fn_mic',
            group: 'toolkit',
            help: `A micrographs.star file to select micrographs from.`,
            on_click: (ev) => w_navtab_update({settings: joinstar_particles})
          },
          {
            name: 'fn_data',
            title: 'Select from particles.star',
            widget: 'radio',
            option: '--fn_data',
            group: 'toolkit',
            help: `A particles.star file to select individual particles from.`,
            on_click: (ev) => w_navtab_update({settings: joinstar_particles})
          },
        ]
      },
      {
        name: 'join_star',
        title: 'Join STAR files',
        widget: 'fieldset',
        children: [
          {
            name: 'do_part',
            title: 'Combine particle STAR files',
            widget: 'radio',
            option: '--do_part',
            group: 'toolkit',
            help: 'Set this to Yes if you plan to join particle STAR files',
            on_click: (ev) => w_navtab_update({settings: joinstar_particles})
          },
          {
            name: 'do_mic',
            title: 'Combine micrograph STAR files?',
             widget: 'radio',
            option: '--do_mic',
            group: 'toolkit',
            help: 'Set this to Yes if you plan to join micrograph STAR files',
            on_click: (ev) => w_navtab_update({settings: joinstar_micrographs})
          },
          {
            name: 'do_mov',
            title: 'Combine movie STAR files',
            widget: 'radio',
            option: '--do_mov',
            group: 'toolkit',
            help: 'Set this to Yes if you plan to join movie STAR files',
            on_click: (ev) => w_navtab_update({settings: joinstar_movies})
          },
        ]
      },
      {
        name: 'mask',
        title: 'Mask creation',
        widget: 'fieldset',
        children : [
          {
            name: 'do_micrographs',
            title: 'Mask creation',
            option: '--do_micrographs',
            widget: 'radio',
            group: 'toolkit',
            help: 'Set this to Yes if you plan to import raw micrographs',
            on_click: (ev) => w_navtab_update({settings: raw_settings})
          },
          {
            name: 'do_micrographs',
            title: 'Mask creation for 3D helical volume',
            option: '--do_micrographs',
            widget: 'radio',
            group: 'toolkit',
            help: 'Set this to Yes if you plan to import raw micrographs',
            on_click: (ev) => w_navtab_update({settings: raw_settings})
          },
        ]
      },
      {
        name: 'extras',
        title: 'Extras',
        widget: 'fieldset',
        children : [
          {
            name: 'crop',
            title: 'Crop/Pad 3D map',
            widget: 'radio',
            group: 'toolkit',
            help: 'Set this to Yes if you plan to import raw micrographs',
          },
          {
            name: 'resize',
            title: 'Resize 3D map',
            widget: 'radio',
            group: 'toolkit',
            help: 'Set this to Yes if you plan to import raw micrographs',
          },
          {
            name: 'do_micrographs',
            title: 'External',
            option: '--do_micrographs',
            widget: 'radio',
            group: 'toolkit',
            help: 'Set this to Yes if you plan to import raw micrographs',
            on_click: (ev) => w_navtab_update({settings: raw_settings})
          },
        ]
      }
    ]
  },
  {
    name: 'settings',
    icon: 'bi-tools',
    title: 'Settings',
    widget: 'navtab',
    children: []
  },
  {
    name: 'running',
    icon: 'bi-send',
    title: 'Running',
    widget: 'navtab',
    children: [
      {
        name: 'queue_settings',
        title:  'Queue settings',
        widget: 'fieldset',
        children: [
          {
            name: 'submit_queue',
            title:  'Submit to queue?',
            widget: 'bool',
          },
          {
            name: 'queue_name',
            title:  'Queue name',
            widget: 'text',
          },
          {
            name: 'queue_command',
            title:  'Queue submit command',
            widget: 'text',
          },
          {
            name: 'submit_script',
            title:  'Standard submission script',
            widget: 'text',
          },
          {
            name: 'min_core',
            title:  'Minimum dedicated cores per node',
            default: 4,
            widget: 'int',
          },
        ]
      },
      {
        name: 'misc',
        title:  'Misc.',
        widget: 'fieldset',
        children: [
          {
            name: 'extra_args',
            title:  'Additional arguments',
            default: '',
            widget: 'text',
          },
          {
            name: 'alias',
            title:  'Job alias',
            widget: 'text',
          },
        ]
      },
      {
        name: 'extra_args',
        title:  'Run',
        widget: 'fieldset',
        children: [
          {
            name: 'schedule',
            title:  'Schedule',
            widget: 'button',
          },
          {
            name: 'run',
            title:  'Run!',
            widget: 'button',
          },
          {
            name: 'continue',
            title:  'Continue',
            widget: 'button',
          },
        ]
      },
      {
        name: 'command',
        title:  'Check command',
        widget: 'details',
        children: []
      },

    ]
  }
];


