[build-system]
requires = ["hatchling>=1.27", "versioningit"]
build-backend = "hatchling.build"

[project]
name = "grinder"
dynamic = ["version"]
authors = [{name = "Jean-Christophe Taveau", email = "jean-christophe.taveau@u-bordeaux.fr"}]
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
description = "A FastAPI package for file tree and websockets"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.136.1",
    "mrcfile>=1.5.4",
    "numpy>=2.4.0",
    "pandas>=3.0.0",
    "polars[all]>=1.39.0",
    "typer>=0.24.0",
    "uvicorn>=0.41.0",
    "star_gate @ git+https://github.com/crazybiocomputing/star_gate@main"
]

[tool.hatch.version]
source = "versioningit"

[tool.hatch.metadata]
allow-direct-references = true

[project.scripts]
# This creates a command line tool, e.g., 'start-my-server'
grinder = "grinder.main:app"

